import Foundation

/// 365 morning journaling prompts — one for each day of the year.
enum JournalPrompts {

    /// The prompt for the current day. Cached so the date math runs once per day
    /// instead of on every render that reads `JournalPrompts.today`.
    static var today: String {
        let day = Calendar.current.ordinality(of: .day, in: .year, for: Date()) ?? 1
        if let cached = cachedToday, cached.day == day {
            return cached.prompt
        }
        let prompt = all[(day - 1) % all.count]
        cachedToday = (day, prompt)
        return prompt
    }

    private static var cachedToday: (day: Int, prompt: String)?

    static let all: [String] = [
        "What's one thing you're grateful for this morning?",
        "What's your main focus for today?",
        "What would make today feel like a win?",
        "Who do you want to show up as today?",
        "What's one thing you've been putting off?",
        "How are you feeling right now, honestly?",
        "What's something good that happened yesterday?",
        "What do you need more of in your life right now?",
        "What's been draining your energy lately?",
        "What's one small win from this week?",
        "What are you looking forward to today?",
        "What would you tell yourself from a year ago?",
        "What do you want to let go of today?",
        "What habit do you want to build this month?",
        "Who is someone you appreciate, and why?",
        "What's something you learned recently?",
        "What's your biggest challenge right now?",
        "What does a good day look like for you?",
        "What's one thing you want to do better today?",
        "What's been on your mind that you haven't said out loud?",
        "What are you most proud of right now?",
        "What would make you feel more at peace today?",
        "What goal have you been working toward?",
        "What's one thing you can do today for someone else?",
        "How do you want to feel by the end of today?",
        "What are you curious about lately?",
        "What does rest look like for you right now?",
        "What's one thing you can say no to today?",
        "What's been making you smile lately?",
        "What do you need to hear this morning?",
        "What's a fear you'd like to face this week?",
        "When did you last feel truly relaxed?",
        "What's one promise you want to keep to yourself today?",
        "What's something you're avoiding, and why?",
        "What would your calmest self do today?",
        "What's a small joy you often overlook?",
        "Who has shaped who you are today?",
        "What does success mean to you right now?",
        "What's a boundary you need to set?",
        "What part of your routine actually serves you?",
        "What would make this week feel meaningful?",
        "What's something you're ready to forgive?",
        "What energizes you the most?",
        "What's a strength you forget you have?",
        "What's one thing you'd do if you weren't afraid?",
        "How have you grown in the last year?",
        "What's weighing on you that you can put down?",
        "What does your ideal morning feel like?",
        "What are you holding onto that no longer fits?",
        "What would you like more time for?",
        "What's a recent moment you felt fully present?",
        "What do you want to remember about this season of life?",
        "What's a kindness someone showed you recently?",
        "What's a story you tell yourself that isn't true?",
        "What would make today 1% better?",
        "What's something you're looking forward to this month?",
        "Where do you feel most like yourself?",
        "What's a question you've been sitting with?",
        "What does your body need today?",
        "What's one thing you can simplify?",
        "What are you tolerating that you shouldn't?",
        "What made you laugh recently?",
        "What's a goal that excites and scares you?",
        "What do you want to create today?",
        "Who do you want to reach out to?",
        "What's a comfort you're grateful for?",
        "What would you do today if it were your last free day?",
        "What's a lesson this week has taught you?",
        "What are you ready to begin?",
        "What's something you keep meaning to try?",
        "What does courage look like for you today?",
        "What's draining you that you can change?",
        "What part of your life feels most alive?",
        "What's a decision you've been postponing?",
        "What's one thing you're doing just for you today?",
        "What does balance mean to you right now?",
        "What's a memory that always makes you smile?",
        "What are you learning to accept?",
        "What's something small you can celebrate today?",
        "Who do you want to be more like, and why?",
        "What's a worry you can release this morning?",
        "What would make you feel proud tonight?",
        "What's something you're grateful your past self did?",
        "What do you want your evening to feel like?",
        "What's a habit you'd like to gently break?",
        "What's giving you hope right now?",
        "What's one way you can be kinder to yourself today?",
        "What's a conversation you need to have?",
        "What feels heavy, and what feels light?",
        "What's a goal you've outgrown?",
        "What do you want to say yes to today?",
        "What's something you admire in others?",
        "What's a risk worth taking right now?",
        "What part of today are you dreading, and why?",
        "What's a simple pleasure you can enjoy today?",
        "What would make you feel more grounded?",
        "What's something you're figuring out?",
        "What's a value you want to live by today?",
        "What's been quietly bothering you?",
        "What do you want to give more attention to?",
        "What's a win you haven't acknowledged yet?",
        "What does a meaningful day require of you?",
        "What are you ready to ask for help with?",
        "What's something you want to protect your time for?",
        "What's a fear that's smaller than it feels?",
        "What would the most patient version of you do today?",
        "What's something you're excited to learn?",
        "What's been feeding your stress?",
        "What's one thing within your control today?",
        "What do you want to feel less of?",
        "What's a relationship you want to nurture?",
        "What's a truth you've been avoiding?",
        "What's the kindest thing you can do today?",
        "What would make this an easier day?",
        "What's a belief that's been holding you back?",
        "What are you proud of about how you handled something hard?",
        "What's one thing you can finish today?",
        "What does your future self need from you now?",
        "What's a moment of beauty you noticed recently?",
        "What are you ready to stop apologizing for?",
        "What's something you want to do more slowly?",
        "What's been giving you energy lately?",
        "What would make you feel accomplished today?",
        "What's a small step toward a big goal?",
        "What do you want to remember on a hard day?",
        "What's a habit that's quietly improving your life?",
        "What's something you need to grieve or release?",
        "What does your gut tell you about a current decision?",
        "What's a way you've surprised yourself recently?",
        "What do you want today to teach you?",
        "What's something you keep comparing, and can you stop?",
        "What's a part of yourself you're learning to like?",
        "What would make you feel rested this week?",
        "What's one thing you want to be honest about?",
        "What's a small adventure you can have today?",
        "What's something you're outgrowing?",
        "What do you want to make space for?",
        "What's a compliment you'd give yourself today?",
        "What's been pulling your attention away from what matters?",
        "What's a goal you can break into smaller pieces?",
        "What does showing up for yourself look like today?",
        "What's something you used to want that you don't anymore?",
        "What's a feeling you've been pushing away?",
        "What would you attempt if you knew you'd be okay?",
        "What's a way you can move your body today?",
        "What's a tradition or ritual that grounds you?",
        "What's one assumption you can question today?",
        "What do you want to be remembered for?",
        "What's a small mess you can clean up today?",
        "What's been bringing you a sense of meaning?",
        "What do you want to forgive yourself for?",
        "What's a way you can connect with someone today?",
        "What's something you're proud to have survived?",
        "What would make this morning feel calmer?",
        "What's a skill you'd love to develop?",
        "What's been distracting you from your goals?",
        "What do you want more clarity on?",
        "What's a kind truth you can tell yourself?",
        "What's something you want to do less perfectly and more often?",
        "What's a place that makes you feel at home?",
        "What are you ready to recommit to?",
        "What's one worry you can hand off for today?",
        "What's a way you've been brave recently?",
        "What do you want to nourish today: body, mind, or spirit?",
        "What's something you keep relearning?",
        "What would make today feel lighter?",
        "What's a thought you want to think more often?",
        "What's a small risk you can take today?",
        "What's been worth your time lately?",
        "What's a need you've been ignoring?",
        "What do you want to approach with more patience?",
        "What's a moment you'd like to recreate?",
        "What's something you can let be good enough today?",
        "What's a hope you're nurturing quietly?",
        "What do you want to protect about your peace?",
        "What's a question you'd ask your wiser self?",
        "What's one thing that went better than expected?",
        "What's a way you can show up for your future self?",
        "What's something you're learning to trust?",
        "What do you want to spend less energy on?",
        "What's a relationship that helps you grow?",
        "What's a fear you can examine instead of obey?",
        "What does a gentle start to the day look like?",
        "What's one thing you can do with full attention today?",
        "What's been quietly going well?",
        "What do you want to say to someone you miss?",
        "What's a part of your routine you can enjoy more?",
        "What's something you want to be less reactive about?",
        "What's a goal that feels worth the effort?",
        "What would make you feel more like yourself today?",
        "What's a habit you want to protect on busy days?",
        "What's something you can appreciate about right now?",
        "What's a way you can ask for what you need?",
        "What's been keeping you up at night, and why?",
        "What's a strength you can lean on today?",
        "What do you want to leave behind this week?",
        "What's a small kindness you can do for yourself this morning?",
        "What's something you want to understand better?",
        "What does your ideal afternoon look like?",
        "What's a worry that hasn't come true?",
        "What's one thing you can do today that your future self will thank you for?",
        "What's a feeling you want to make room for?",
        "What's a way you can slow down today?",
        "What's something you've been brave enough to start?",
        "What's a belief about yourself you're updating?",
        "What do you want to be intentional about today?",
        "What's a memory you're grateful for?",
        "What's something you can release control of today?",
        "What's a way you can be more present with people you love?",
        "What's a goal that aligns with who you're becoming?",
        "What's been recharging you?",
        "What's a small win you can set up for tomorrow?",
        "What's something you can choose not to carry today?",
        "What do you want to give yourself permission to do?",
        "What's a lesson from a recent mistake?",
        "What's a way you can make today feel special?",
        "What's something you're learning to do differently?",
        "What's a feeling you want to chase today?",
        "What's a part of your life you want to tend to?",
        "What's something you keep putting off that would feel great to finish?",
        "What's a way you can be gentle with someone today?",
        "What's a thought pattern you want to interrupt?",
        "What's a reason to be hopeful this morning?",
        "What's a small comfort you can give yourself?",
        "What do you want today to add up to?",
        "What's something you're ready to outgrow?",
        "What's a way you can honor your limits today?",
        "What's a moment you felt proud of recently?",
        "What do you want to be curious about today?",
        "What's a way you can simplify a decision?",
        "What's something you can do today that scares you a little?",
        "What's a worry you can talk yourself through?",
        "What do you want more of, and how can you make room?",
        "What's a quality you want to grow in yourself?",
        "What's been worth slowing down for?",
        "What's a small risk that could pay off?",
        "What do you want to forgive in someone else?",
        "What's a way you can be more honest with yourself today?",
        "What's something you can do today just because it brings you joy?",
        "What's a habit that's been holding you back?",
        "What do you want to feel grateful for tonight?",
        "What's a way you've changed for the better?",
        "What's something you're ready to take seriously?",
        "What's a worry you can postpone until later?",
        "What do you want your energy to go toward today?",
        "What's a kind assumption you can make about someone?",
        "What's a way you can make space for stillness?",
        "What's something you want to remember to appreciate?",
        "What's a fear you can shrink by naming it?",
        "What do you want to be proud of by this evening?",
        "What's a way you can take care of your mind today?",
        "What's something small that would make your space feel better?",
        "What's a goal that's quietly important to you?",
        "What's a way you can show yourself patience today?",
        "What's been giving your days more meaning?",
        "What's something you can choose to enjoy today?",
        "What's a way you can reconnect with an old interest?",
        "What do you want to handle with more grace?",
        "What's a small promise you can keep today?",
        "What's a way you can lighten someone's day?",
        "What's something you're learning to appreciate about your life?",
        "What's a worry you can replace with a plan?",
        "What's a way you can move toward a dream today?",
        "What do you want to release before the day begins?",
        "What's a strength you want to use more often?",
        "What's a way you can be present in a small moment today?",
        "What's something you can do today to feel more organized?",
        "What's a thought that brings you comfort?",
        "What do you want to protect your energy from today?",
        "What's a way you can be braver in a small thing?",
        "What's something you can let go of needing to be perfect?",
        "What's a moment you want to savor today?",
        "What's a way you can be kinder in your self-talk?",
        "What do you want to learn from today, whatever happens?",
        "What's a small joy you can plan into your day?",
        "What's a way you can show up fully for one task?",
        "What's something you're ready to ask for?",
        "What's a worry you can meet with compassion?",
        "What's a way you can honor your values today?",
        "What's something you can do today to invest in your health?",
        "What's a way you can welcome the unexpected today?",
        "What do you want to be more deliberate about?",
        "What's a small change that would make a big difference?",
        "What's a way you can give yourself a break today?",
        "What's something you've been grateful to have learned the hard way?",
        "What do you want today's effort to build toward?",
        "What's a way you can be more open today?",
        "What's a feeling you want to leave behind?",
        "What's something you want to do with more love today?",
        "What's a way you can make peace with uncertainty?",
        "What do you want to celebrate, no matter how small?",
        "What's a way you can choose calm over hurry?",
        "What's something you're proud to be working on?",
        "What's a way you can be a little more yourself today?",
        "What do you want to remember when things get busy?",
        "What's a small step you can take toward feeling better?",
        "What's a way you can offer yourself encouragement today?",
        "What's something you're ready to believe about yourself?",
        "What's a way you can make room for what matters most?",
        "What do you want to approach with fresh eyes today?",
        "What's a kindness you can carry with you today?",
        "What's a way you can end today feeling at peace?",
        "What's something you want to thank your body for?",
        "What's a way you can make today count?",
        "What's a worry you can trade for trust?",
        "What's something you want to do bravely today?",
        "What's a way you can be more grateful in the small moments?",
        "What do you want to give your best attention to?",
        "What's a way you can be gentle with your progress?",
        "What's something you're looking forward to becoming?",
        "What's a way you can choose hope this morning?",
        "What do you want this day to give you a chance to do?",
        "What's a way you can honor how far you've come?",
        "What's something you want to nurture in yourself this year?",
        "What's a way you can start today with intention?",
        "What's a small thing you can do today that aligns with your bigger why?",
        "What do you want to make a little more time for?",
        "What's a way you can treat today as a fresh start?",
        "What's something you're grateful is part of your life?",
        "What's a way you can be the calm you're looking for?",
        "What do you want to carry into tomorrow?",
        "What's a way you can be proud of simply showing up today?",
        "What's something you want to remember about who you are?",
        "What's a way you can make this morning yours?",
        "What's something you've been brave about that you haven't credited yourself for?",
        "What would make you feel genuinely cared for today?",
        "What's a thought you'd like to wake up to more often?",
        "What's one expectation you can loosen today?",
        "What's a way you can bring more play into your day?",
        "What's something you're slowly making peace with?",
        "What would your future self thank you for starting today?",
        "What's a small ritual that makes your mornings better?",
        "What's a way you can listen to yourself more closely today?",
        "What's something you want to approach with an open heart?",
        "What's a worry you can set a time to deal with later?",
        "What's a way you can celebrate someone today?",
        "What's something you've been craving more of?",
        "What's a way you can make a hard task feel smaller?",
        "What's a part of your day you can fully enjoy?",
        "What do you want to give yourself credit for?",
        "What's a way you can be more honest about what you want?",
        "What's something you're ready to stop waiting for?",
        "What's a way you can protect a little quiet today?",
        "What's a strength you've built through a hard time?",
        "What's something you can do today that feels like a fresh page?",
        "What's a way you can be more forgiving of your pace?",
        "What's a feeling you want to invite in this morning?",
        "What's something small you can do to feel proud tonight?",
        "What's a way you can show up for a goal even when it's hard?",
        "What's something you keep learning to trust about yourself?",
        "What's a way you can soften your inner critic today?",
        "What's a moment you can choose to be fully here for?",
        "What's something you're grateful you didn't give up on?",
        "What's a way you can make today a little kinder than yesterday?",
        "What's a thought that helps you feel steady?",
        "What's something you want to do with more courage?",
        "What's a way you can welcome rest without guilt?",
        "What's a part of your life that deserves more gratitude?",
        "What's a way you can keep a promise to yourself this week?",
        "What's something you're ready to begin believing is possible?",
        "What's a way you can make peace with where you are?",
        "What's a small light you can hold onto today?",
        "What's a way you can move through today with more ease?",
        "What's something you hope this year teaches you?",
        "What's a way you can begin today exactly as you are?"
    ]
}
